export const departmentsWithTeams = {
  Ministry: [
    "Workforce Admin",
    "Ministry Team leadership",
    "Leadership Effectiveness",
    "Leadership Recruitment",
    "Leadership Training",
    "Pastoral Care",
    "Discipleship, Bible Study and Prayer",
    "Call Centre",
    "Recruitment and Assimilation",
    "Career and Finance",
    "Medical Ministry",
    "Elders Care",
    "Prison Ministry",
    "Kids Support",
    "House of Dorcas",
    "Legal Aid",
  ],
  Membership: [
    "Benevolence",
    "Call Center",
    "Celebration",
    "Ceremonies",
    "Data Management",
    "Growth Track",
    "Guest Welcome",
    "Info Hub",
    "Interactors",
    "New Convert",
    "Weddings",
  ],
  "General Service": ["Admin and Facility", "Communications (DMU)", "Finance"],
  "Interactive Groups": [
    "Singles Ministry",
    "Women of Wisdom",
    "Men of Harvest",
  ],
  Maturity: [
    "Discipleship Event",
    "Group Partnership",
    "Testimony Capture",
    "Courses HSDC",
    "Content Development (Resources)",
    "Prayer and Bible Study",
  ],
  Missions: [
    "Evangelism",
    "God's encounter",
    "HSAP",
    "Invest and Invite",
    "NLP",
    "Publicity",
  ],
  District: [
    "Royal Priesthoods Community",
    "Ogudu/Alapere Community",
    "Bethel Community",
    "Harmony Community",
    "Shomolu 2 Community",
    "Lightbearers Community",
    "Trailblazer Community",
    "Praise Community",
    "Gbagada Estate Community",
    "Anagkazo Community",
    "Sunrise Community"
  ],
  Programs: [
    "Exalted Tribe",
    "Drama",
    "Sapphire ET",
    "Musicians",
    "Diamond ET",
    "Emerald ET",
    "Pearl ET",
    "Greeters",
    "Greeters - Team Yahweh",
    "Greeters - Team Jireh",
    // "Greeters 1st team",
    // "Greeters 2nd team",
    // "Greeters 3rd team",
    // "Greeters 4th team",
    "Harvesters Intelligence Unit",
    "Media-Administration",
    "Media-Experience",
    "Media-Graphics",
    "Media-Light",
    "Media-Livestream",
    "Media-Photo (Capturing)",
    "Media-Text & Timing",
    "Media-Video",
    "Media-Visuals",
    "Media-Audio Production",
    "Media-Equipment Management",
    "Program Management",
    "Protocol",
    "Sound",
    "Quality Assurance",
    "Unveil",
    "Traffic",
    "Ushering - Bimpe",
    "Ushering - Queen",
    "Ushering - Iyaanu",
    "Ushering - Tosin",
    "Ushering - Kofoworola",
    "Ushering",
    "Venue Management",
    "Venue Management - Feyisayo Phillip team",
    "Venue Management - Tosin Agbetuyi team",
    "Venue Management - Zeina team",
    "Venue Management - Emmanuel team",
    "Venue Management - Boluwatife team",
    "Programs Admin Team",
  ],
  Mission: ["Sub team-Missions", "Target Missions"],
  "Next Gen": [
    "Reach and Partnership - Stirhouse",
    "Learning and Development - Stirhouse",
    "Programming and Environment - Stirhouse",
    "Administration - Stirhouse",
    "Reach and Partnership - Kidszone",
    "New Workers - Kidszone",
    "Administration - Kidszone",
    "Programming and Environment - Kidszone",
    "Learning and Development - Kidszone",
  ],
//   "Pastoral Leaders": ["Pastoral Leaders"],
//   "Directional Leader": ["Directional Leader"],
};

export const teamsSummary = [
  {
    label: "All Teams",
    value: "All",
  },
  {
    label: "Maturity (Prayer, Midweek)",
    value: "Maturity",
  },
  {
    label: "General Service (Finance, Facility, Etc)",
    value: "General Service",
  },
  {
    label: "Ministry (Leadership & Dev, Workforce Etc)",
    value: "Ministry",
  },
  {
    label: "Membership (Growth Track, Etc)",
    value: "Membership",
  },
  {
    label: "Programs (Choir, Ushers, Etc)",
    value: "Programs",
  },
  { label: "Next Gen (Kidzone & Stir House)", value: "Next Gen" },
  {
    label: "Mission (NLP, HSAP, Evangelism, Etc)",
    value: "Missions",
  },
  { label: "District", value: "District" },
  {
    label: "Interactive Groups (Singles, WOW, Etc)",
    value: "Interactive Groups",
  },
//   {
//     label: "Pastoral Leaders",
//     value: "Pastoral Leaders",
//   },
//   { label: "Directional Leaders", value: "Directional Leader" },
];